import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ChevronDown, Globe2, Menu, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetClose, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";

const nav = [
  ["Home", "/"], ["About", "/about"], ["VITY", "/vity"], ["Products", "/products"],
  ["EAEU Distribution", "/eaeu-distribution"], ["B2B Partnership", "/partnership"], ["Contact", "/contact"],
] as const;

function Brand() { return <Link to="/" aria-label="5D Group home" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-md bg-primary font-display text-sm font-bold text-primary-foreground">5D</span><span><strong className="block font-display text-[15px] leading-none">5D GROUP</strong><span className="mt-1 block text-[9px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">Pharma · Nutrition</span></span></Link>; }

export function SiteHeader() {
  const [languageOpen, setLanguageOpen] = useState(false);
  return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="section-shell flex h-[76px] items-center justify-between gap-5"><Brand /><nav className="hidden items-center gap-5 xl:flex">{nav.map(([label, to]) => <Link key={to} to={to} activeOptions={{ exact: to === "/" }} className="text-[13px] font-semibold text-muted-foreground transition hover:text-primary" activeProps={{ className: "text-primary" }}>{label}</Link>)}</nav><div className="hidden items-center gap-2 lg:flex"><div className="relative"><Button variant="ghost" size="sm" onClick={() => setLanguageOpen(!languageOpen)} aria-expanded={languageOpen}><Globe2 /> EN <ChevronDown className="size-3" /></Button>{languageOpen && <div className="absolute right-0 top-10 w-36 rounded-md border bg-popover p-2 shadow-lg"><div className="rounded px-3 py-2 text-sm font-semibold text-foreground">English</div><div className="px-3 py-2 text-xs text-muted-foreground">Русский · Soon</div><div className="px-3 py-2 text-xs text-muted-foreground">Հայերեն · Soon</div></div>}</div><Button asChild size="sm"><Link to="/contact">Partner inquiry <ArrowUpRight /></Link></Button></div><Sheet><SheetTrigger asChild><Button size="icon" variant="outline" className="lg:hidden" aria-label="Open navigation"><Menu /></Button></SheetTrigger><SheetContent><SheetHeader><SheetTitle><Brand /></SheetTitle></SheetHeader><nav className="mt-10 flex flex-col gap-1">{nav.map(([label, to]) => <SheetClose asChild key={to}><Link to={to} className="border-b border-border py-4 text-base font-semibold text-foreground">{label}</Link></SheetClose>)}</nav><div className="mt-8 text-sm text-muted-foreground"><Globe2 className="mb-2 size-4" />English · Русский soon · Հայերեն soon</div></SheetContent></Sheet></div></header>;
}

export function SiteFooter() { return <footer className="border-t bg-surface"><div className="section-shell grid gap-10 py-12 md:grid-cols-[1.3fr_1fr_1fr]"><div><Brand /><p className="mt-5 max-w-sm text-sm leading-6 text-muted-foreground">Exclusive VITY Vitamins & Supplements partner across the Eurasian Economic Union.</p></div><div><p className="text-sm font-bold text-foreground">Navigate</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm text-muted-foreground"><Link to="/about">About</Link><Link to="/vity">VITY</Link><Link to="/products">Products</Link><Link to="/product-categories">Categories</Link><Link to="/partnership">Partnership</Link><Link to="/contact">Contact</Link></div></div><div><p className="text-sm font-bold text-foreground">Business inquiries</p><a href="mailto:5dgrouppharma@gmail.com" className="mt-4 block text-sm font-semibold text-primary">5dgrouppharma@gmail.com</a><p className="mt-3 text-sm text-muted-foreground">Pharmaceutical & Nutraceutical Distribution</p></div></div><div className="border-t border-border"><div className="section-shell flex flex-col gap-2 py-5 text-xs text-muted-foreground sm:flex-row sm:justify-between"><span>© 2026 5D Group. All rights reserved.</span><span>Dietary supplements are not medicines.</span></div></div></footer>; }

export function SiteLayout({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-background"><SiteHeader /><main>{children}</main><SiteFooter /></div>; }